sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: LG/9j0YjD2p4AnlgBXNqFW/85mSQv4IoChN/YT1HmCV4cROg2pCxAuZLIxTHIK6yrLBGCih/F1us199BKm0Dce6on9Fh2ifq+Zr4AaTazi4I9xJnNsPsBCh8Vcy19fX0AqBHTx+Ga3aFuwTerQ37JY8eh1eTHPBXOARY9/CuWYpFIEeWmKmrFiTmZRGsYdGUcTRk1MA/lIRAW0549CGW7Xss1glGHZLzVf3LTi5vy+bvo8NANxxaeiDm5eQZUtHWbLN2X2auCpBC54OK3bbmZEaewwGj33/RsDJGz1E8Mvq0cklm86QBqvnjdnvGbWCNPt1iCE0x4sg3Gf/c0GjOZmIPuEb+OfqUaFenZVpWjjOIWJ0zMYDEHP1PTe3nkGfGpadPmf35drDH7ErEkdRkXah5GTCFV/NdYyDxp4F/oHg4ANQA6uIOEP5Ghh0wk/ksI8VwmM33ZN8KjjyA0q6TXzBBoAB9o2rkNei8SCer+X594p6b4rChoRnNtEXOBmgosSf6ddTSu0toY4quv8MElLK6iw11ZEUg3i21e8bXtwcDM9VYSEwvGSaXgB9Gr7TT8J0WDl5Wb0ji8rc3nIa9wQmzkO4nSpWawuPB+j92Dvc3N8daszmRZDHvWfh2rdgsZqF269uPLPc8mN8/RCdECYHr1j8DMpj7mdzfeQAQOZo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Greenmantle_559
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy